Polish translation file
AfonsoFGarcia/hass-bluecon pull request #8
Opened 2024-09-14 14:53 UTC by markopolopb

2024-09-15 18:23 UTC, AfonsoFGarcia requested changes

2024-09-15 18:23 UTC, AfonsoFGarcia commented on custom_components/bluecon/translations/pl.json
> +        "title": "Sign-in with Fermax Blue account",
Hi @markopolopb!

Thanks for your contribution. Can you please update this label to match the `data.username` one? 

Thanks!

2024-09-19 09:00 UTC, markopolopb commented
Hi, file updated.

2024-09-19 23:27 UTC, AfonsoFGarcia approved these changes

2024-09-19 23:27 UTC, merged